=== camenduru/magic-time-tost/schema.json
{
  "$schema": "http://json-schema.org/draft-04/hyper-schema#",
  "type": "object",
  "properties": {
    "readme": {
      "type": "string",
      "title": "MagicTime: Time-lapse Video Generation Models as Metamorphic Simulators",
      "author": "Shenghai Yuan, Jinfa Huang, Yujun Shi, Yongqi Xu, Ruijie Zhu, Bin Lin, Xinhua Cheng, Li Yuan, Jiebo Luo",
      "code": "https://github.com/PKU-YuanGroup/MagicTime",
      "paper": "https://arxiv.org/abs/2404.05014",
      "page": "https://pku-yuangroup.github.io/MagicTime/",
      "jupyter": "https://github.com/camenduru/MagicTime-jupyter",
      "post": "https://x.com/camenduru/status/1779120764400112122",
      "api": "https://github.com/camenduru/tost-api-examples/blob/main/v1/magic-time.ipynb",
      "tags": [
        "Text to Video"
      ],
      "widget": "readme"
    },
    "prompt": {
      "type": "string",
      "description": "Prompt",
      "widget": "textarea"
    },
    "negative_prompt": {
      "type": "string",
      "description": "Negative Prompt",
      "widget": "textarea"
    },
    "num_inference_steps": {
      "type": "integer",
      "readOnly": "true",
      "description": "Inference Steps"
    },
    "guidance_scale": {
      "type": "number",
      "readOnly": "true",
      "description": "Guidance Scale"
    },
    "video_length": {
      "type": "integer",
      "readOnly": "true",
      "description": "Video Length"
    },
    "width": {
      "type": "integer",
      "readOnly": "true",
      "description": "Width"
    },
    "height": {
      "type": "integer",
      "readOnly": "true",
      "description": "Height"
    }
  },
  "buttons": [
    {
      "id": "enter",
      "label": "ðŸ¥ª Enter"
    }
  ]
}

=== camenduru/magic-time-tost/model.json
{
    "prompt": "An ice cube is melting.",
    "negative_prompt": "lowres, text, error, cropped, worst quality, low quality, jpeg artifacts, ugly, duplicate, morbid, mutilated, out of frame, extra fingers, mutated hands, poorly drawn hands, poorly drawn face, mutation, deformed, blurry, dehydrated, bad anatomy, bad proportions, extra limbs, cloned face, disfigured, gross proportions, malformed limbs, missing arms, missing legs, extra arms, extra legs, fused fingers, too many fingers, long neck, username, watermark, signature",
    "width": 512,
    "height": 512,
    "num_inference_steps": 25,
    "guidance_scale": 8.5,
    "video_length": 16
  }
